[project]
name = "maxmsp-mcp"
version = "0.1.0"
description = "Max/MSP integration through Model Context Protocol"
dependencies = [
    "mcp[cli]",
    "python-socketio",
    "aiohttp",
]
requires-python = ">=3.11"
